### ISSUE TITLE
If I run then This happend

### ISSUE THREAD

**Issue by Nirmal846** [Squuv/Nitrx#5]
λ bash install.sh
======= NITRX INSTALL =======
 [+] Nitrx Will Be Installed In Your System
 [+] Installing Packages ...
install.sh: line 12: pip: command not found
 [+] Checking directories ...
 [+] Installing ...
 [+] Tool successfully installed and will start in 5s!
 [+] You can execute tool by typing python Nitrx.py
install.sh: line 19: /c/Users/Dr.Pitamber.Dass/AppData/Local/Microsoft/WindowsApps/python: Permission denied

**Comment by EloniX-X** [comment]
you have some anti python thing on your computer probably
